services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: YOUR_DATABASE
      MYSQL_USER: DATABASE_USER
      MYSQL_PASSWORD: "PASSWORD"
      MYSQL_ROOT_HOST: '%'
      LANG: C.UTF-8
      TZ: UTC  # Add timezone environment variable
    command:
      - --bind-address=0.0.0.0
      - --skip-name-resolve
      - --default-authentication-plugin=caching_sha2_password  # Update authentication plugin
      - --log_error_verbosity=1  # Reduce error logging verbosity
    ports:
      - "4306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - /etc/timezone:/etc/timezone:ro  # Add timezone files
      - /etc/localtime:/etc/localtime:ro
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-proot"]   # Use IP instead of localhost
      interval: 5s
      timeout: 5s
      retries: 25
      start_period: 60s

  fastapi:
    build: .
    container_name: docker-container-fastapi
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql+pymysql://DATABASE_USER:PASSWORD@mysql-db:3###/YOUR_DATABASE"
    ports:
      - "8000:8000"
    networks:
      - app_network
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app_network
    depends_on:
      - fastapi
      
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - app_network
    depends_on:
      - prometheus    
    
networks:
  app_network:
    driver: bridge

        

volumes:
  mysql_data:
  grafana_data: